db.url=jdbc:mysql://localhost:3306/Student_db1
db.username=root
db.password=Rishabh9161@
db.driver=com.mysql.cj.jdbc.Driver
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.idleTimeoutMs=30000
db.pool.connectionTimeoutMs=20000
